version: '3.3'

services:
  grafana:
    image: grafana/grafana-enterprise:latest
    container_name: grafana
    user: "0"
    restart: always
    environment:
      - GF_LOG_MODE=console file
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
      - GF_SECURITY_ALLOW_EMBEDDING=true
    volumes:
      - ./conf/:/etc/grafana/
      - ./data/:/var/lib/grafana/
      - ./logs/:/var/log/grafana/
    ports:
      - 3000:3000
