version: "3"

services:
  mkdocs:
    image: mkdocs:v1
    restart: unless-stopped
    command: serve --dev-addr 0.0.0.0:8080 --config-file /build/mkdocs.yml
    volumes:
      - ./notes:/build

  proxy:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/mkdocs.conf
      - ./nginx/htpasswd:/etc/nginx/.htpasswd:ro
    ports:
      - 8080:8080


  notes-tunnel:
     image: cloudflare/cloudflared:latest
     restart: unless-stopped
     command: tunnel --no-autoupdate run --token ${MKD_CF_TOKEN}
