global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'VM1 prometheus'
    static_configs:
      - targets: ['${PROMETHEUS_HOST}:9090']

  - job_name: 'VM1 docker'
    static_configs:
      - targets: ['${VM1_DOCKER_HOST}:9323']

  - job_name: 'VM2 docker'
    static_configs:
      - targets: ['${VM2_HOST}:9323']
