version: "3.3"

services:
  db:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_RPWD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PWD}
    volumes:
      - ./data:/var/lib/mysql
#      - ./conf:/etc/mysql/
    ports:
      - 3306:3306

  php_myadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    links:
      - db
    environment:
      - PMA_ARBITRARY=1
      - PMA_PORT=3306
    ports:
      - 8080:80
